name: Continuous Integration

# Controls when the workflow will run
on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ] # Also trigger on pull requests targeting main

jobs:
  # This job builds the Docker images to verify the Docker setup
  build_docker_images:
    name: Build Docker Images
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for improved build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker images using docker-compose
      # This step verifies that the Dockerfiles and docker-compose.yml are configured correctly
      # and that the application images can be built successfully.
      # We don't push the images anywhere in this basic CI setup.
      - name: Build images with Docker Compose
        run: docker compose build

      # Optional: Add linting or testing steps here in the future
      # - name: Lint code
      #   run: |
      #     cd backend && npm ci && npm run lint
      #     cd ../frontend && npm ci && npm run lint
      # - name: Run tests
      #   run: |
      #     # Add commands to run backend and frontend tests
      #     echo "Tests would run here"
